language: python

os:
  - linux

python:
  - "3.5"

install:
  - pip install .

# Run tests
script:
  - py.test tests/*.py -v
  - tests/structure_field_test.sh
  - tests/fastStructure_field_test.sh
  - tests/maverick_field_test.sh
